--Zad 1
CREATE TABLE DOKUMENTY(
    ID NUMBER(12) PRIMARY KEY,
    DOKUMENT CLOB
);

--Zad 2
DECLARE
    TEXT_CONT CLOB :='';
BEGIN
    FOR COUNTER IN 1..10000 LOOP
        TEXT_CONT := TEXT_CONT || 'Oto tekst.';
    END LOOP;
    
    INSERT INTO DOKUMENTY(ID, DOKUMENT) VALUES(1, TO_CLOB(TEXT_CONT));
    
END;

--Zad 3
--a)
SELECT * FROM DOKUMENTY;

--b)
SELECT UPPER(DOKUMENT) FROM DOKUMENTY;

--c)
SELECT LENGTH(DOKUMENT) FROM DOKUMENTY;

--d)
SELECT DBMS_LOB.GETLENGTH(DOKUMENT) FROM DOKUMENTY;

--e)
SELECT SUBSTR(DOKUMENT, 5,1000) FROM DOKUMENTY;

--f)
SELECT DBMS_LOB.SUBSTR(DOKUMENT, 1000, 5) FROM DOKUMENTY;

--Zad 4
INSERT INTO DOKUMENTY(ID, DOKUMENT) VALUES(2, EMPTY_CLOB());

--Zad 5
INSERT INTO DOKUMENTY(ID, DOKUMENT) VALUES(3, NULL);

--Zad 6
--a)
SELECT * FROM DOKUMENTY;

--b)
SELECT UPPER(DOKUMENT) FROM DOKUMENTY;

--c)
SELECT LENGTH(DOKUMENT) FROM DOKUMENTY;

--d)
SELECT DBMS_LOB.GETLENGTH(DOKUMENT) FROM DOKUMENTY;

--e)
SELECT SUBSTR(DOKUMENT, 5,1000) FROM DOKUMENTY;

--f)
SELECT DBMS_LOB.SUBSTR(DOKUMENT, 1000, 5) FROM DOKUMENTY;

--Zad 7
SELECT * FROM ALL_DIRECTORIES;

--Zad 8
DECLARE
    LOBSS clob;
    FIL BFILE := BFILENAME('ZSBD_DIR', 'dokument.txt');
    DOFFSET INTEGER := 1;
    SOFFSET INTEGER := 1;
    IDENT INTEGER := 0;
    MESS INTEGER := null;
BEGIN
    SELECT DOKUMENT INTO LOBSS FROM DOKUMENTY
    WHERE ID = 2 FOR UPDATE;
    DBMS_LOB.fileopen(FIL, DBMS_LOB.file_readonly);
    DBMS_LOB.LOADCLOBFROMFILE(LOBSS, FIL, DBMS_LOB.LOBMAXSIZE, DOFFSET, SOFFSET, 873, IDENT, MESS);
    DBMS_LOB.FILECLOSE(FIL);
    DBMS_LOB.FILECLOSE(FIL);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Status operacji: '||MESS);
END;

--Zad 9
UPDATE DOKUMENTY 
SET DOKUMENT = TO_CLOB(BFILENAME('ZSBD_DIR', 'dokument.txt'))
WHERE ID = 3;

--Zad 10
SELECT * FROM DOKUMENTY;

--Zad 11
SELECT LENGTH(DOKUMENT) FROM DOKUMENTY;

--Zad 12
DROP TABLE DOKUMENTY;

--Zad 13
CREATE OR REPLACE PROCEDURE CLOB_CENSOR(LOBSS IN OUT CLOB, TEXT_TO_CENSOR IN VARCHAR2)
IS
    CENSORED_TEXT VARCHAR2(250);
    TEXT_POSITION INTEGER;
BEGIN
    CENSORED_TEXT := '';
    FOR COUNTER IN 1..LENGTH(TEXT_TO_CENSOR) LOOP
        CENSORED_TEXT := CENSORED_TEXT || '.';
    END LOOP;
    
    TEXT_POSITION := DBMS_LOB.INSTR(LOBSS, TEXT_TO_CENSOR);
    WHILE TEXT_POSITION <> 0
        LOOP
            DBMS_LOB.WRITE(LOBSS, LENGTH(TEXT_TO_CENSOR), TEXT_POSITION, CENSORED_TEXT);
            TEXT_POSITION := DBMS_LOB.INSTR(LOBSS, TEXT_TO_CENSOR);
        END LOOP;
END CLOB_CENSOR;

--Zad 14
CREATE TABLE BIOGRAPHIES_COPY AS SELECT * FROM ZSBD_TOOLS.BIOGRAPHIES;

SELECT * FROM BIOGRAPHIES_COPY;

DECLARE
    LOBSS CLOB;
BEGIN
    SELECT BIO INTO LOBSS
    FROM BIOGRAPHIES_COPY
    FOR UPDATE;
    
    CLOB_CENSOR(LOBSS, 'Cimrman');
    COMMIT;
END;

SELECT * FROM BIOGRAPHIES_COPY;

--Zad 15
DROP TABLE BIOGRAPHIES_COPY;
